name: fluxo
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_bloc: ^9.0.0
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  code_builder: ^4.10.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4

flutter:
  uses-material-design: true
